#Application Name
spring.application.name=resume-parser-service

# Server
server.port=8093

# Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2

# Optional Timeout
spring.ai.ollama.chat.options.temperature=0.2

# Logging
logging.level.org.springframework.ai=DEBUG

# UTF-8 Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
