package org.airesume.aiservice.service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.airesume.aiservice.dto.jobResponseDTO;
import org.airesume.aiservice.dto.resumeResponseDTO;
import org.airesume.aiservice.util.ScoreCalculatorUtil;
//import org.springframework.ai.chat.prompt.ChatOptions;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.ai.chat.client.ChatClient;
import org.airesume.aiservice.dto.aiRequestDTO;
import org.airesume.aiservice.dto.aiResponseDTO;
//import org.springframework.ai.ollama.OllamaOptions;
import java.util.*;

import java.util.ArrayList;
import java.util.List;

@Service
public class aiService {
    private final RestTemplate restTemplate;
    private final ChatClient  chatClient;

    public aiService(RestTemplate restTemplate, ChatClient.Builder builder) {
        this.restTemplate = restTemplate;
        this.chatClient =builder.build();
    }
    public aiResponseDTO analyzeResume(aiRequestDTO requestDTO){
        //IMPP
        String key = requestDTO.getResumeId() + "-" + requestDTO.getJobId();

        //fetch resume by resumeID
    resumeResponseDTO resume=restTemplate.getForObject("http://localhost:8092/api/resumes/" + requestDTO.getResumeId(),
            resumeResponseDTO.class);
    //fetch Job By Id
        jobResponseDTO job=restTemplate.getForObject("http://localhost:8091/api/jobdesc/" + requestDTO.getJobId(), jobResponseDTO.class);
        //fetch resume skills
        List<String> resumeSkills=ScoreCalculatorUtil.convertStringToList(resume.getSkills());
        //fetch job description
        String description=job.getDescription();
        //AI Extracts Skills from description
        List<String> jobSkills=extractSkillsUsingAI(description);
        // MATCHED SKILLS
        List<String> matchedSkills = ScoreCalculatorUtil.getMatchedSkills(resumeSkills, jobSkills);
        // MISSING SKILLS
        List<String> missingSkills =ScoreCalculatorUtil.getMissingSkills(resumeSkills, jobSkills);
        // ATS SCORE
        double atsScore = ScoreCalculatorUtil.calculateAtsScore(matchedSkills, jobSkills);
        // RECOMMENDATION
        String recommendation = ScoreCalculatorUtil.generateRecommendation(atsScore);

        //AI Response DTO
        aiResponseDTO  responseDTO=new aiResponseDTO();
        responseDTO.setResumeId(requestDTO.getResumeId());
        responseDTO.setJobId(requestDTO.getJobId());
        responseDTO.setMatchedSkills(matchedSkills);
        responseDTO.setMissingSkills(missingSkills);
        responseDTO.setAtsScore(atsScore);
        responseDTO.setRecommendation(recommendation);

        return responseDTO;

    }

    //AI Method for Extracting Skills
    public List<String> extractSkillsUsingAI(String description)
    {
        String prompt = """
You are a strict JSON generator.

TASK:
Extract technical skills ONLY from the job description.

RULES:
- Return ONLY valid JSON array
- No extra text
- No markdown
- No duplicates
- No variations of same skill
- Normalize skills to standard form (e.g., "Spring Boot", "Java", "SQL")

OUTPUT FORMAT:
["skill1","skill2","skill3"]

JOB DESCRIPTION:
""" + description;

    String response= chatClient.prompt().user(prompt).call().content();

        //Checking whether the response generated by AI is correct or not
//        if (response == null || !response.trim().startsWith("[") || !response.trim().endsWith("]")) {
//            throw new RuntimeException("Invalid AI response: " + response);
//        }

        response = response.trim();

        System.out.println("AI RAW RESPONSE = " + response);

        response = response.trim()
                .replace("```json", "")
                .replace("```", "")
                .replace("\n", "")
                .replace("\r", "");

        System.out.println("AI RAW RESPONSE = " + response);

        //Check and understand properly

        //Normalize AI Skills also

        ObjectMapper mapper=new ObjectMapper();
    try{
//        List<String> aiSkills =
//                mapper.readValue(response, new TypeReference<List<String>>(){});

        List<String> aiSkills;
        if(response.startsWith("[")) {
            aiSkills = mapper.readValue(response, new TypeReference<List<String>>() {});
        }
        else if(response.startsWith("{"))
        {
            Map<String,Object> map = mapper.readValue(response, Map.class);

            Object skillsObj = map.get("skills");
            if(skillsObj == null) {
                throw new RuntimeException("skills key not found in AI response");
            }
            aiSkills = (List<String>) skillsObj;;
        }
        else
        {
            throw new RuntimeException("Invalid AI response: " + response);
        }
        List<String> cleanedSkills = new ArrayList<>();
        for (String skill : aiSkills) {
            String normalized = ScoreCalculatorUtil.normalizeSkill(skill);
            if (!cleanedSkills.contains(normalized)) {
                cleanedSkills.add(normalized);
            }
        }
        // Sort manually (no streams)
        for (int i = 0; i < cleanedSkills.size(); i++) {
            for (int j = i + 1; j < cleanedSkills.size(); j++) {
                if (cleanedSkills.get(i).compareTo(cleanedSkills.get(j)) > 0) {
                    String temp = cleanedSkills.get(i);
                    cleanedSkills.set(i, cleanedSkills.get(j));
                    cleanedSkills.set(j, temp);
                }
            }
        }
        return cleanedSkills;
    }
    catch(Exception e){
        e.printStackTrace();
        return new ArrayList<>();
    }
}
}
